const movies = [
  "Mentalista",
  "Mentirosas nueva",
  "Chernovyl",
  "Fringe",
  "Evangelion",
  "Señor de los anillos 2 extendida",
  "El padrino",
  "Terminator 2",
  "Saw VI",
  "La maldición",
  "Piratas del caribe 4",
  "Código davinci",
  "Prision break",
  "Ad Astra",
  "Halloween resurrección",
  "12 princesas",
  "Evolution",
  "Bojack",
  "Desencanto simpsons",
  "Dark",
  "Susurros del corazón",
  "Nausicaa",
  "Arriety",
  "Desaparecido",
  "Mi vecino totoro",
  "La quinta ola",
  "Mapaches",
  "The simpsons",
  "Resident evil 5",
  "Kiki entregas a domicilio",
  "La colina de las amapolas",
  "Cuentos de terramar",
  "28 weeks",
  "Mr pickles",
  "Aun se lo que hicieron el verano pasado",
  "Novia de Chuky",
  "Demonic",
  "All quiet in the north front",
  "Bullet Train",
  "A Star is born",
  "The calm beyond",
  "Liar Liar",
  "Aladin live action",
  "El rey leon",
  "Tijuana",
  "Sucession",
  "3096 days",
  "El huesped",
  "End of days",
  "Mamma mia",
  "De ladron a policia",
  "Batman 3",
  "65",
  "Joker",
  "Cabin Fever",
  "Godzilla vs Kong",
  "Sherlock Holmes 2",
  "Matrix 1",
  "Ace Ventura 2",
  "Mission Imposible 1",
  "Nobody",
  "Top gun",
  "Found footage",
  "Las crónicas del miedo",
  "Tenet",
  "Separation",
  // https://www.radiotimes.com/movies/dcau-movies-order/
  // https://editorial.rottentomatoes.com/guide/dc-animated-movies-in-order/
  "SUPERMAN: DOOMSDAY (2007)",
  "The Batman (Patkinson)",
  "Narcos",
  "Doom",
  "El Infierno",
  "La ley de herodes",
  "Memento",
  "What if",
  "Iron Man 3",
  "Capitan America 1",
  "Hulk",
  "Amsterdam",
  "RBD por siempre",
  "Retribution",
  "Otra pelicula de huevos y un pollo",
  "The others",
  "Los caballeros",
  "Snowpiercer",
  "Resident Evil Death Island",
  "True Detective S1",
  "Funny People",
  "DumbMoney",
  "Sinister 2",
  "Dune",
  "The Northman",
  "Zapatero a tus zapatos",
  "El Portal del más alla",
  "Time",
  "Perros de reserva",
  "Suzume",
  "MobPysycho 100",
  "La idea de ti",
  "Darkest hour",
  "Concrete Utopia",
  "Barbie Fairytopia",
  "Barbie Pegaso",
  "Jerry and Marge Go Large",
  "El examen",
  "Jujutsu Kaisen",
  "The Sinner",
  "The beekeper",
  "Rise of the Planet of the Apes",
  "Monolith",
  "Mr. Deeds",
  "Truman",
  "Godzilla Minus One",
  "Chuky",
  "Estación Zombie Busan Train 2",
  "Wedding Crashers",
  "Dumb and Dumber 2",
  "Distric 9",
  "Sausage Party: Foodtopia",
  "Circus Du Soleil: Without a net",
  "Futurama",
  "The Wire",
  "Migration",
  "Tarot",
  "Lost",
  "Amarte duele",
  "Demon Slayer",
  "Virus",
  "The Girls on the Train",
  "La invasión",
  "The Holdovers",
  "La Tumba de las Luciernagas",
  "The Tatami Galaxy",
  "The Penguin",
  "The Exorcism of Emily Rose",
  "Panic Room",
  "Hunter x Hunter",
  "Robot Dreams",
  "Courtois, the Return of the Number 1",
  "Deception (2008)",
  "Salems Lot",
  "El Niño y la Garza",
  "Uzumaki",
  "Winnie The Pooh - Blood and Honey",
  "Death Sentence",
  "Kinds of Kindness",
  "Hold your breath",
  "Dark Souls",
  "Strange Way of Life",
];

const random = Math.floor(Math.random() * movies.length);

var moviePicked = document.getElementById("moviePicked");

moviePicked.textContent += movies[random];
