const movies = [
	"Game of thrones", 
	"Mentalista", 
	"Mentirosas", 
	"Chernovyl", 
	"Fringe", 
	"Evangelion", 
	"Señor de los anillos extendida", 
	"Merlina", 
	"El padrino", 
	"Terminaitor", 
	"Saw", 
	"La maldición", 
	"Piratas del caribe", 
	"Resurrección", 
	"Código davinci", 
	"Hereditario", 
	"Priosion break", 
	"Mentes criminales", 
	"Ad Astra", 
	"Inquebrantable", 
	"Plan de vuelo", 
	"El dia qué la tierra se detuvo", 
	"Bárbaro", 
	"Una navidad de locos", 
	"Halloween", 
	"12 princesas", 
	"Crimen perfecto", 
	"Evolution", 
	"Titanes del pacifico", 
	"Grinch", 
	"Documental de juan pa", 
	"Bojack", 
	"La princesa mononoke", 
	"Baby", 
	"Desencanto", 
	"Dark", 
	"Encantada y desencantada", 
	"Libranos del mal", 
	"Increíble castillo vagabundo", 
	"Susurros del corazón", 
	"Marnie", 
	"Black summer", 
	"Nausicaa", 
	"Arriety", 
	"Desaparecido", 
	"Pongo", 
	"Mi vecino totoro", 
	"El castillo en el cielo", 
	"Fractura", 
	"Diamantes en bruto", 
	"La quinta ola", 
	"El regreso del gato", 
	"La noche del demonio", 
	"Mapaches", 
	"Se levanta el viento", 
	"Roughen", 
	"The simpsons", 
	"365 días", 
	"RRR", 
	"El puente maldito", 
	"Residen evil", 
	"Fractura"]

const random = Math.floor(Math.random() * movies.length)

var moviePicked = document.getElementById("moviePicked");

moviePicked.textContent += movies[random]