const movies = [
	"Game of thrones", 
	"Mentalista", 
	"Mentirosas nueva", 
	"Chernovyl", 
	"Fringe", 
	"Evangelion", 
	"Señor de los anillos extendida", 
	"Merlina", 
	"El padrino", 
	"Terminator 2", 
	"Saw", 
	"La maldición", 
	"Piratas del caribe", 
	"Resurrección", 
	"Código davinci", 
	"Hereditario", 
	"Prision break", 
	"Mentes criminales", 
	"Ad Astra", 
	"Inquebrantable",
	"El dia qué la tierra se detuvo",
	"Halloween", 
	"12 princesas", 
	"Crimen perfecto", 
	"Evolution", 
	"Titanes del pacifico",
	"Documental de juan pa", 
	"Bojack",
	"Desencanto simpsons", 
	"Dark", 
	"Encantada y desencantada", 
	"Libranos del mal",
	"Susurros del corazón",
	"Nausicaa", 
	"Arriety", 
	"Desaparecido", 
	"Ponyo", 
	"Mi vecino totoro", 
	"El castillo en el cielo", 
	"Fractura",
	"La quinta ola",
	"La noche del demonio 2", 
	"Mapaches",
	"The simpsons",
	"RRR", 
	"El puente maldito", 
	"Resident evil",
	"Kiki entregas a domicilio",
	"La colina de las amapolas",
	"Puedo escuchar el mar",
	"Porco Rosso",
	"Cuentos de terramar",
	"Just married",
	"Face off",
	"A cure for wellness",
	"The happening",
	"28 weeks",
	"Coda",
	"Mr pickles",
	"Aun se lo que hicieron el verano pasado",
	"Emily in Paris",
	"You",
	"The Last of Us",
	"Triunfos robados 3"]

const random = Math.floor(Math.random() * movies.length)

var moviePicked = document.getElementById("moviePicked");

moviePicked.textContent += movies[random]